---
- name: deploy prometheus server
  remote_user: ec2-user
  hosts: all # allにしたら動いた。prometheusだと対象サーバが見つからないと
  become: yes
  roles:
    - role: common
      tags: common
    - role: prometheus
      tags: prometheus
