---
- name: initial-setup-confirm
  stat: 
    path: /etc/prometheus/blackbox_exporter/blackbox_exporter.yml
  register: result # 存在していればresultという変数にTrueを、存在していなければFalseを格納します。
- name: download blackbox_exporter
  get_url:
    url: https://github.com/prometheus/blackbox_exporter/releases/download/v0.19.0/blackbox_exporter-0.19.0.linux-amd64.tar.gz
    dest: /tmp
  when: not result.stat.exists # resultがFalseの場合のみ処理を実行します。
- name: unarchive blackbox_exporter-0.19.0.linux-amd64.tar.gz
  unarchive:
    src: /tmp/blackbox_exporter-0.19.0.linux-amd64.tar.gz
    dest: /tmp   # /tmp/blackbox_exporter-0.19.0.linux-amd64
    remote_src: yes
  when: not result.stat.exists # resultがFalseの場合のみ処理を実行します。
- name: prometheus directory created
  file:
    path: "/etc/prometheus/blackbox_exporter"
    state: directory
    owner: "root"
    group: "root"
    mode: "775"
- name: blackbox_exporteディレクトリに解凍したファイルを移動
  shell: |
    mv /tmp/blackbox_exporter-0.19.0.linux-amd64/* /etc/prometheus/blackbox_exporter
  when: not result.stat.exists # resultがFalseの場合のみ処理を実行します。
- name: generate blackbox_exporter.service config file
  copy:
    src: blackbox_exporter.service
    dest: /usr/lib/systemd/system/blackbox_exporter.service
- name: generate blackbox_exporter config file
  copy:
    src: blackbox_exporter.yml
    dest: /etc/prometheus/blackbox_exporter/blackbox_exporter.yml
- name: prometheusサービスの再起動
  systemd:
    name: blackbox_exporter
    state: restarted
    enabled: yes
