---
- name: yum install go
  yum:
    name:
      - golang-1.15.14
    state: present # インストールされている場合はskip
    # state: latest
- name: copy goenv.sh
  copy:
    src: "goenv.sh"
    dest: "/etc/profile.d/goenv.sh"
    mode: 0755
    backup: no
    owner: root
    group: root
  #loop:
  #  - { src: roles/go/files/goenv.sh, dest: . }
 
#- name: source /etc/profile.d/goenv.sh
#  shell: | 
#    bash -lc "source /etc/profile.d/goenv.sh" # -lはログイン状態のシェルで-cは引数のコマンドを実行する
#  #ignore_errors: yes
