---
- name: yum install go
  yum:
    name:
      - golang-1.15.14
    state: present # インストールされている場合はskip
    # state: latest
- name: copy .bash_profile
  copy:
    src: "ec2-user.bash_profile"
    dest: "~/.bash_profile"
    # dest: "/home/ec2-user/.bash_profile"
    mode: 0755
    backup: no
    #owner: root
    #group: root
  become_user: ec2-user # 環境変数の都合で設定
- name: download test_httpserver.go
  get_url:
    url: https://raw.githubusercontent.com/kichiram/golang/main/testgo/test_httpserver.go
    dest: /tmp
- name: source /home/ec2-user/.bash_profile
  shell: |
    source /home/ec2-user/.bash_profile
  become_user: ec2-user # 環境変数の都合で設定
- name: go get
  shell: |
    go get -u github.com/prometheus/client_golang/prometheus
  become_user: ec2-user # 環境変数の都合で設定
- name: build
  shell: |
    go build test_httpserver.go
  args:
    chdir: /tmp
  become_user: ec2-user # 環境変数の都合で設定
- name: update binary
  copy:
    src: /tmp/test_httpserver
    dest: /usr/local/bin/test_httpserver
    remote_src: yes # このyesオプションがないとサーバで探してくれない。ローカルを探す
    mode: 0755
- name: generate test_httpserver.service config file
  copy:
    src: test_httpserver.service
    dest: /usr/lib/systemd/system/test_httpserver.service
- name: test_httpserverサービスの再起動
  systemd:
    name: test_httpserver.service
    state: restarted
    enabled: yes
