---
- name: yum install go
  yum:
    name:
      - golang-1.15.14
    state: present # インストールされている場合はskip
    # state: latest
- name: GOROOT directory created
  file:
    path: "/usr/local/go"
    state: directory
    owner: "root"
    group: "root"
    mode: "775"
- name: GOPATH directory created
  file:
    path: "/go"
    state: directory
    owner: "root"
    group: "root"
    mode: "775"
- name: copy goenv.sh
  copy:
    src: "goenv.sh"
    dest: "/etc/profile.d/goenv.sh"
    mode: 0755
    backup: no
    owner: root
    group: root
- name: download test_httpserver.go
  get_url:
    url: https://raw.githubusercontent.com/kichiram/golang/main/testgo/test_httpserver.go
    dest: /tmp
- name: source /etc/profile.d/goenv.sh
  shell: |
    bash -lc "source /etc/profile.d/goenv.sh" # -lはログイン状態のシェルで-cは引数のコマンドを実行する
  #ignore_errors: yes
- name: go get 
  shell: |  
    bash -lc "go get -u github.com/prometheus/client_golang/prometheus" # 追加する場合は行追加すればOK
- name: build
  shell: |
    go build test_httpserver.go
  args:
    chdir: /tmp
- name: update binary
  copy:
    src: /tmp/test_httpserver
    dest: /usr/local/bin/
    remote_src: yes # このyesオプションがないとサーバで探してくれない。ローカルを探す
    mode: 0755
- name: generate test_httpserver.service config file
  copy:
    src: test_httpserver.service
    dest: /usr/lib/systemd/system/test_httpserver.service
- name: test_httpserverサービスの再起動
  systemd:
    name: test_httpserver.service
    state: restarted
    enabled: yes
